# Generated by Django 3.1.13 on 2021-11-20 16:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='lorem', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
