version: '3'

services:
  django:
    container_name: django3
    build:
      context: .
      args:
        MODE: development
    command: python manage.py runserver 0.0.0.0:9000
    restart: always
    volumes:
      - ./django/:/app/
    env_file:
      - .env
    environment:
      MODE: development
    ports:
      - 9000:9000

volumes:
  postgres_data:
