configmap:
  data:
    ENVIRONMENT: "hlg"
    POSTGRES_DB: "db_hlg_my_project_database"

ingress:
  hosts:
    - host: my-app-hlg.viavarejo.com.br
      paths:
        - path: /
  tls:
    - hosts:
      - my-app-hlg.viavarejo.com.br

resources:
  app:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 256Mi
