strictness: veryhigh

ignore-paths:
  - migrations

uses:
  - django

pep8:
  full: true
  options:
    max-line-length: 120

pylint:
  full: true

pyflakes:
  disable:
    - F401

mccabe:
  disable:
    - MC0001
