# Generated by Django 3.1.13 on 2021-11-04 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('text', models.CharField(max_length=512, null=True, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='relevance',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ajudometro'),
        ),
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.ManyToManyField(related_name='reports', to='reports.Comentary', verbose_name='Comentários'),
        ),
    ]
