# Generated by Django 3.1.13 on 2021-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20211104_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='reports', to='reports.Comentary', verbose_name='Comentários'),
        ),
    ]
