# Generated by Django 3.1.13 on 2021-11-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20211114_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='reports', to='reports.Comentary', verbose_name='Comentários'),
        ),
    ]
