# Generated by Django 3.1.13 on 2021-11-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='relevance',
        ),
    ]
