# Generated by Django 3.1.13 on 2021-11-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_report_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='token',
            field=models.CharField(default='huvpzyj3kmm6t7hqotah', max_length=64, verbose_name='token'),
            preserve_default=False,
        ),
    ]
