name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Seting up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('dev.txt') }}

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r docker/requirements/dev.txt

      - name: Running Tests
        run: |
            python django/manage.py test

      - name: Running Linting 
        run: |
            cd django
            prospector .
