name: Deployment

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotenv
        run: |
            cp .env.sample .env
            whoami

      - name: Run server
        run: |
            docker-compose up -d
